/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegistrationData = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'referrer' : IDL.Opt(IDL.Principal),
  'displayName' : IDL.Text,
  'dateOfBirth' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ManualPaymentRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Time = IDL.Int;
export const ManualPaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : ManualPaymentRequestStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'gameSpin' : IDL.Null,
  'referralBonus' : IDL.Null,
  'couponBonus' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'description' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'outcallType' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'bonusGranted' : IDL.Bool,
  'couponCode' : IDL.Opt(IDL.Text),
  'credits' : IDL.Nat,
  'referrer' : IDL.Opt(IDL.Principal),
  'kCheckerState' : IDL.Bool,
  'displayName' : IDL.Text,
  'referralBonusAvailed' : IDL.Bool,
  'dateOfBirth' : IDL.Text,
  'isEligibleForKidDiscount' : IDL.Bool,
  'lastUpdateTime' : IDL.Int,
  'creationTime' : IDL.Int,
  'bonusCouponAvailed' : IDL.Bool,
  'balanceUpdates' : IDL.Vec(IDL.Int),
  'profileSetupCompleted' : IDL.Bool,
  'transactions' : IDL.Vec(Transaction),
});
export const ManualPaymentConfig = IDL.Record({
  'qrImageReference' : IDL.Text,
  'instructions' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const GameOutcome = IDL.Variant({
  'tiger' : IDL.Null,
  'crit' : IDL.Null,
  'miss' : IDL.Null,
  'dragon' : IDL.Null,
});
export const SpinResult = IDL.Record({
  'user' : IDL.Principal,
  'balanceAfterSpin' : IDL.Nat,
  'profit' : IDL.Int,
  'outcome' : GameOutcome,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addValidCouponCode' : IDL.Func([IDL.Text], [], []),
  'adminUpdateCredits' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
  'approveManualPayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeInitialProfileSetup' : IDL.Func([RegistrationData], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createManualPaymentRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'declineManualPayment' : IDL.Func([IDL.Nat], [], []),
  'getAdminUserBalance' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getAllManualPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(ManualPaymentRequest)],
      ['query'],
    ),
  'getAllUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditPackages' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'credits' : IDL.Nat,
            'name' : IDL.Text,
            'priceInrMultiplier' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getHouseEdgeValue' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getManualPaymentConfig' : IDL.Func(
      [],
      [IDL.Opt(ManualPaymentConfig)],
      ['query'],
    ),
  'getManualPaymentRequest' : IDL.Func(
      [IDL.Nat],
      [ManualPaymentRequest],
      ['query'],
    ),
  'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyCreditTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyManualPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(ManualPaymentRequest)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserCreditTransactions' : IDL.Func(
      [IDL.Principal, IDL.Bool, IDL.Bool],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidCouponCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'removeValidCouponCode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setHouseEdgeValue' : IDL.Func([IDL.Nat], [], []),
  'setManualPaymentConfig' : IDL.Func([ManualPaymentConfig], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'spinWheel' : IDL.Func([], [SpinResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegistrationData = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'referrer' : IDL.Opt(IDL.Principal),
    'displayName' : IDL.Text,
    'dateOfBirth' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ManualPaymentRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Time = IDL.Int;
  const ManualPaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : ManualPaymentRequestStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'gameSpin' : IDL.Null,
    'referralBonus' : IDL.Null,
    'couponBonus' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'description' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'outcallType' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'bonusGranted' : IDL.Bool,
    'couponCode' : IDL.Opt(IDL.Text),
    'credits' : IDL.Nat,
    'referrer' : IDL.Opt(IDL.Principal),
    'kCheckerState' : IDL.Bool,
    'displayName' : IDL.Text,
    'referralBonusAvailed' : IDL.Bool,
    'dateOfBirth' : IDL.Text,
    'isEligibleForKidDiscount' : IDL.Bool,
    'lastUpdateTime' : IDL.Int,
    'creationTime' : IDL.Int,
    'bonusCouponAvailed' : IDL.Bool,
    'balanceUpdates' : IDL.Vec(IDL.Int),
    'profileSetupCompleted' : IDL.Bool,
    'transactions' : IDL.Vec(Transaction),
  });
  const ManualPaymentConfig = IDL.Record({
    'qrImageReference' : IDL.Text,
    'instructions' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const GameOutcome = IDL.Variant({
    'tiger' : IDL.Null,
    'crit' : IDL.Null,
    'miss' : IDL.Null,
    'dragon' : IDL.Null,
  });
  const SpinResult = IDL.Record({
    'user' : IDL.Principal,
    'balanceAfterSpin' : IDL.Nat,
    'profit' : IDL.Int,
    'outcome' : GameOutcome,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addValidCouponCode' : IDL.Func([IDL.Text], [], []),
    'adminUpdateCredits' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
    'approveManualPayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeInitialProfileSetup' : IDL.Func([RegistrationData], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createManualPaymentRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'declineManualPayment' : IDL.Func([IDL.Nat], [], []),
    'getAdminUserBalance' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getAllManualPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(ManualPaymentRequest)],
        ['query'],
      ),
    'getAllUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditPackages' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'credits' : IDL.Nat,
              'name' : IDL.Text,
              'priceInrMultiplier' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getHouseEdgeValue' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getManualPaymentConfig' : IDL.Func(
        [],
        [IDL.Opt(ManualPaymentConfig)],
        ['query'],
      ),
    'getManualPaymentRequest' : IDL.Func(
        [IDL.Nat],
        [ManualPaymentRequest],
        ['query'],
      ),
    'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyCreditTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyManualPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(ManualPaymentRequest)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserCreditTransactions' : IDL.Func(
        [IDL.Principal, IDL.Bool, IDL.Bool],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidCouponCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'removeValidCouponCode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setHouseEdgeValue' : IDL.Func([IDL.Nat], [], []),
    'setManualPaymentConfig' : IDL.Func([ManualPaymentConfig], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'spinWheel' : IDL.Func([], [SpinResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };