/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ManualPaymentRequest {
    id: bigint;
    status: ManualPaymentRequestStatus;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    user: Principal;
    description?: string;
    timestamp: Time;
    outcallType?: string;
    amount: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ManualPaymentConfig {
    qrImageReference: string;
    instructions: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface RegistrationData {
    couponCode?: string;
    referrer?: Principal;
    displayName: string;
    dateOfBirth: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SpinResult {
    user: Principal;
    balanceAfterSpin: bigint;
    profit: bigint;
    outcome: GameOutcome;
}
export interface UserProfile {
    id: string;
    bonusGranted: boolean;
    couponCode?: string;
    credits: bigint;
    referrer?: Principal;
    kCheckerState: boolean;
    displayName: string;
    referralBonusAvailed: boolean;
    dateOfBirth: string;
    isEligibleForKidDiscount: boolean;
    lastUpdateTime: bigint;
    creationTime: bigint;
    bonusCouponAvailed: boolean;
    lastSpinResult?: SpinResult;
    balanceUpdates: Array<bigint>;
    profileSetupCompleted: boolean;
    transactions: Array<Transaction>;
}
export enum GameOutcome {
    tiger = "tiger",
    crit = "crit",
    miss = "miss",
    dragon = "dragon"
}
export enum ManualPaymentRequestStatus {
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal",
    gameSpin = "gameSpin",
    referralBonus = "referralBonus",
    couponBonus = "couponBonus"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addValidCouponCode(couponCode: string): Promise<void>;
    adminUpdateCredits(user: Principal, newBalance: bigint): Promise<bigint>;
    approveManualPayment(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeInitialProfileSetup(registrationData: RegistrationData): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createManualPaymentRequest(amount: bigint): Promise<bigint>;
    declineManualPayment(requestId: bigint): Promise<void>;
    getAdminUserBalance(user: Principal, _keep: bigint): Promise<bigint>;
    getAllManualPaymentRequests(): Promise<Array<ManualPaymentRequest>>;
    getAllUserTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCreditPackages(): Promise<Array<{
        credits: bigint;
        name: string;
        priceInrMultiplier: bigint;
    }>>;
    getHouseEdgeValue(): Promise<bigint>;
    getLeaderboard(): Promise<Array<[Principal, bigint]>>;
    getManualPaymentConfig(): Promise<ManualPaymentConfig | null>;
    getManualPaymentRequest(requestId: bigint): Promise<ManualPaymentRequest>;
    getMyBalance(): Promise<bigint>;
    getMyCreditTransactions(): Promise<Array<Transaction>>;
    getMyManualPaymentRequests(): Promise<Array<ManualPaymentRequest>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserCreditTransactions(user: Principal, onlyWithdrawals: boolean, onlyDeposits: boolean): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isValidCouponCode(couponCode: string): Promise<boolean>;
    removeValidCouponCode(couponCode: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setHouseEdgeValue(value: bigint): Promise<void>;
    setManualPaymentConfig(config: ManualPaymentConfig): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    spinWheel(): Promise<SpinResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { GameOutcome as _GameOutcome, ManualPaymentConfig as _ManualPaymentConfig, ManualPaymentRequest as _ManualPaymentRequest, ManualPaymentRequestStatus as _ManualPaymentRequestStatus, RegistrationData as _RegistrationData, SpinResult as _SpinResult, StripeSessionStatus as _StripeSessionStatus, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addValidCouponCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addValidCouponCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addValidCouponCode(arg0);
            return result;
        }
    }
    async adminUpdateCredits(arg0: Principal, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCredits(arg0, arg1);
            return result;
        }
    }
    async approveManualPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveManualPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveManualPayment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeInitialProfileSetup(arg0: RegistrationData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeInitialProfileSetup(to_candid_RegistrationData_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeInitialProfileSetup(to_candid_RegistrationData_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createManualPaymentRequest(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createManualPaymentRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createManualPaymentRequest(arg0);
            return result;
        }
    }
    async declineManualPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineManualPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineManualPayment(arg0);
            return result;
        }
    }
    async getAdminUserBalance(arg0: Principal, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserBalance(arg0, arg1);
            return result;
        }
    }
    async getAllManualPaymentRequests(): Promise<Array<ManualPaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllManualPaymentRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllManualPaymentRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditPackages(): Promise<Array<{
        credits: bigint;
        name: string;
        priceInrMultiplier: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditPackages();
            return result;
        }
    }
    async getHouseEdgeValue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouseEdgeValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouseEdgeValue();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getManualPaymentConfig(): Promise<ManualPaymentConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualPaymentConfig();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualPaymentConfig();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManualPaymentRequest(arg0: bigint): Promise<ManualPaymentRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualPaymentRequest(arg0);
                return from_candid_ManualPaymentRequest_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualPaymentRequest(arg0);
            return from_candid_ManualPaymentRequest_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getMyCreditTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCreditTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCreditTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyManualPaymentRequests(): Promise<Array<ManualPaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyManualPaymentRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyManualPaymentRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCreditTransactions(arg0: Principal, arg1: boolean, arg2: boolean): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCreditTransactions(arg0, arg1, arg2);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCreditTransactions(arg0, arg1, arg2);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isValidCouponCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidCouponCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidCouponCode(arg0);
            return result;
        }
    }
    async removeValidCouponCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeValidCouponCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeValidCouponCode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setHouseEdgeValue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHouseEdgeValue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHouseEdgeValue(arg0);
            return result;
        }
    }
    async setManualPaymentConfig(arg0: ManualPaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setManualPaymentConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setManualPaymentConfig(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async spinWheel(): Promise<SpinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.spinWheel();
                return from_candid_SpinResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spinWheel();
            return from_candid_SpinResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_GameOutcome_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameOutcome): GameOutcome {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ManualPaymentRequestStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManualPaymentRequestStatus): ManualPaymentRequestStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ManualPaymentRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManualPaymentRequest): ManualPaymentRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SpinResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpinResult): SpinResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SpinResult]): SpinResult | null {
    return value.length === 0 ? null : from_candid_SpinResult_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ManualPaymentConfig]): ManualPaymentConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    user: Principal;
    description: [] | [string];
    timestamp: _Time;
    outcallType: [] | [string];
    amount: bigint;
}): {
    id: bigint;
    transactionType: TransactionType;
    user: Principal;
    description?: string;
    timestamp: Time;
    outcallType?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n13(_uploadFile, _downloadFile, value.transactionType),
        user: value.user,
        description: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.description)),
        timestamp: value.timestamp,
        outcallType: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.outcallType)),
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bonusGranted: boolean;
    couponCode: [] | [string];
    credits: bigint;
    referrer: [] | [Principal];
    kCheckerState: boolean;
    displayName: string;
    referralBonusAvailed: boolean;
    dateOfBirth: string;
    isEligibleForKidDiscount: boolean;
    lastUpdateTime: bigint;
    creationTime: bigint;
    bonusCouponAvailed: boolean;
    lastSpinResult: [] | [_SpinResult];
    balanceUpdates: Array<bigint>;
    profileSetupCompleted: boolean;
    transactions: Array<_Transaction>;
}): {
    id: string;
    bonusGranted: boolean;
    couponCode?: string;
    credits: bigint;
    referrer?: Principal;
    kCheckerState: boolean;
    displayName: string;
    referralBonusAvailed: boolean;
    dateOfBirth: string;
    isEligibleForKidDiscount: boolean;
    lastUpdateTime: bigint;
    creationTime: bigint;
    bonusCouponAvailed: boolean;
    lastSpinResult?: SpinResult;
    balanceUpdates: Array<bigint>;
    profileSetupCompleted: boolean;
    transactions: Array<Transaction>;
} {
    return {
        id: value.id,
        bonusGranted: value.bonusGranted,
        couponCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.couponCode)),
        credits: value.credits,
        referrer: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.referrer)),
        kCheckerState: value.kCheckerState,
        displayName: value.displayName,
        referralBonusAvailed: value.referralBonusAvailed,
        dateOfBirth: value.dateOfBirth,
        isEligibleForKidDiscount: value.isEligibleForKidDiscount,
        lastUpdateTime: value.lastUpdateTime,
        creationTime: value.creationTime,
        bonusCouponAvailed: value.bonusCouponAvailed,
        lastSpinResult: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.lastSpinResult)),
        balanceUpdates: value.balanceUpdates,
        profileSetupCompleted: value.profileSetupCompleted,
        transactions: from_candid_vec_n10(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    balanceAfterSpin: bigint;
    profit: bigint;
    outcome: _GameOutcome;
}): {
    user: Principal;
    balanceAfterSpin: bigint;
    profit: bigint;
    outcome: GameOutcome;
} {
    return {
        user: value.user,
        balanceAfterSpin: value.balanceAfterSpin,
        profit: value.profit,
        outcome: from_candid_GameOutcome_n23(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ManualPaymentRequestStatus;
    user: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: ManualPaymentRequestStatus;
    user: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ManualPaymentRequestStatus_n8(_uploadFile, _downloadFile, value.status),
        user: value.user,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
} | {
    gameSpin: null;
} | {
    referralBonus: null;
} | {
    couponBonus: null;
}): TransactionType {
    return "deposit" in value ? TransactionType.deposit : "withdrawal" in value ? TransactionType.withdrawal : "gameSpin" in value ? TransactionType.gameSpin : "referralBonus" in value ? TransactionType.referralBonus : "couponBonus" in value ? TransactionType.couponBonus : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiger: null;
} | {
    crit: null;
} | {
    miss: null;
} | {
    dragon: null;
}): GameOutcome {
    return "tiger" in value ? GameOutcome.tiger : "crit" in value ? GameOutcome.crit : "miss" in value ? GameOutcome.miss : "dragon" in value ? GameOutcome.dragon : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n30(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): ManualPaymentRequestStatus {
    return "pending" in value ? ManualPaymentRequestStatus.pending : "approved" in value ? ManualPaymentRequestStatus.approved : "declined" in value ? ManualPaymentRequestStatus.declined : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManualPaymentRequest>): Array<ManualPaymentRequest> {
    return value.map((x)=>from_candid_ManualPaymentRequest_n6(_uploadFile, _downloadFile, x));
}
function to_candid_GameOutcome_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameOutcome): _GameOutcome {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationData_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationData): _RegistrationData {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SpinResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpinResult): _SpinResult {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bonusGranted: boolean;
    couponCode?: string;
    credits: bigint;
    referrer?: Principal;
    kCheckerState: boolean;
    displayName: string;
    referralBonusAvailed: boolean;
    dateOfBirth: string;
    isEligibleForKidDiscount: boolean;
    lastUpdateTime: bigint;
    creationTime: bigint;
    bonusCouponAvailed: boolean;
    lastSpinResult?: SpinResult;
    balanceUpdates: Array<bigint>;
    profileSetupCompleted: boolean;
    transactions: Array<Transaction>;
}): {
    id: string;
    bonusGranted: boolean;
    couponCode: [] | [string];
    credits: bigint;
    referrer: [] | [Principal];
    kCheckerState: boolean;
    displayName: string;
    referralBonusAvailed: boolean;
    dateOfBirth: string;
    isEligibleForKidDiscount: boolean;
    lastUpdateTime: bigint;
    creationTime: bigint;
    bonusCouponAvailed: boolean;
    lastSpinResult: [] | [_SpinResult];
    balanceUpdates: Array<bigint>;
    profileSetupCompleted: boolean;
    transactions: Array<_Transaction>;
} {
    return {
        id: value.id,
        bonusGranted: value.bonusGranted,
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        credits: value.credits,
        referrer: value.referrer ? candid_some(value.referrer) : candid_none(),
        kCheckerState: value.kCheckerState,
        displayName: value.displayName,
        referralBonusAvailed: value.referralBonusAvailed,
        dateOfBirth: value.dateOfBirth,
        isEligibleForKidDiscount: value.isEligibleForKidDiscount,
        lastUpdateTime: value.lastUpdateTime,
        creationTime: value.creationTime,
        bonusCouponAvailed: value.bonusCouponAvailed,
        lastSpinResult: value.lastSpinResult ? candid_some(to_candid_SpinResult_n33(_uploadFile, _downloadFile, value.lastSpinResult)) : candid_none(),
        balanceUpdates: value.balanceUpdates,
        profileSetupCompleted: value.profileSetupCompleted,
        transactions: to_candid_vec_n37(_uploadFile, _downloadFile, value.transactions)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    balanceAfterSpin: bigint;
    profit: bigint;
    outcome: GameOutcome;
}): {
    user: Principal;
    balanceAfterSpin: bigint;
    profit: bigint;
    outcome: _GameOutcome;
} {
    return {
        user: value.user,
        balanceAfterSpin: value.balanceAfterSpin,
        profit: value.profit,
        outcome: to_candid_GameOutcome_n35(_uploadFile, _downloadFile, value.outcome)
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: TransactionType;
    user: Principal;
    description?: string;
    timestamp: Time;
    outcallType?: string;
    amount: bigint;
}): {
    id: bigint;
    transactionType: _TransactionType;
    user: Principal;
    description: [] | [string];
    timestamp: _Time;
    outcallType: [] | [string];
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: to_candid_TransactionType_n40(_uploadFile, _downloadFile, value.transactionType),
        user: value.user,
        description: value.description ? candid_some(value.description) : candid_none(),
        timestamp: value.timestamp,
        outcallType: value.outcallType ? candid_some(value.outcallType) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    referrer?: Principal;
    displayName: string;
    dateOfBirth: string;
}): {
    couponCode: [] | [string];
    referrer: [] | [Principal];
    displayName: string;
    dateOfBirth: string;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        referrer: value.referrer ? candid_some(value.referrer) : candid_none(),
        displayName: value.displayName,
        dateOfBirth: value.dateOfBirth
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameOutcome): {
    tiger: null;
} | {
    crit: null;
} | {
    miss: null;
} | {
    dragon: null;
} {
    return value == GameOutcome.tiger ? {
        tiger: null
    } : value == GameOutcome.crit ? {
        crit: null
    } : value == GameOutcome.miss ? {
        miss: null
    } : value == GameOutcome.dragon ? {
        dragon: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    deposit: null;
} | {
    withdrawal: null;
} | {
    gameSpin: null;
} | {
    referralBonus: null;
} | {
    couponBonus: null;
} {
    return value == TransactionType.deposit ? {
        deposit: null
    } : value == TransactionType.withdrawal ? {
        withdrawal: null
    } : value == TransactionType.gameSpin ? {
        gameSpin: null
    } : value == TransactionType.referralBonus ? {
        referralBonus: null
    } : value == TransactionType.couponBonus ? {
        couponBonus: null
    } : value;
}
function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Transaction>): Array<_Transaction> {
    return value.map((x)=>to_candid_Transaction_n38(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
